title: Decoding neuronal activities in peripheral auditory pathways using deep learning models

description: Our poster will be presented in the afternoon poster session on Nov. 12th at SfN 2023 Neuroscience meeting in the Room WCC Halls A-C, and the poster board number is: X16.

remote_theme: qiubaiying / qiubaiying.github.io

theme: jekyll-theme-cayman
